# Generated by Django 4.1.1 on 2022-09-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userman", "0002_alter_user_options_user_is_staff_user_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="jhon", max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="Doe", max_length=70),
            preserve_default=False,
        ),
    ]
