# Generated by Django 4.1.1 on 2022-09-27 07:01

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
    ]
