# Generated by Django 4.1.1 on 2022-09-27 10:57

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=tinymce.models.HTMLField(verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.CharField(blank=True, max_length=255, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=255, verbose_name="title"),
        ),
    ]
