# Generated by Django 4.1.1 on 2022-09-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blog_description_alter_blog_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="blog-images/"),
        ),
    ]
