# Generated by Django 4.1.1 on 2022-09-28 06:20

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blog_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="ta_description",
            field=tinymce.models.HTMLField(default="test 1"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blog",
            name="ta_title",
            field=models.CharField(default="test 1 desc", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
